version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Uncomment this if you plan to use HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always